### ISSUE TITLE
Need to pass ref

### ISSUE THREAD

**Issue by ogmzh** [FanchenBao/react-native-scroll-indicator#3]
Considered wrapping your component with `forwardRef`? My usecase is that I'd like to pass this component to a `FlatList` but it wants a component that accepts refs.

**Comment by FanchenBao** [comment]
Do you have a code snippet of your use case? I personally have no encountered a conflict with `forwardRef`.

**Comment by ogmzh** [comment]
Can't reproduce the ts compiler complaint anymore, but i swear i had it complain about refs not being able to get passed to your scroll view from the `renderScrollComponent` of flatlist... sorry...

**Comment by FanchenBao** [comment]
That's okay. No worries. If the problem shows up again, feel free to reopen this issue.
