### ISSUE TITLE
Scroll content with indicator

### ISSUE THREAD

**Issue by msakturkoglu** [FanchenBao/react-native-scroll-indicator#5]
I should be able to scroll content via clicking/touching on indicator

**Comment by donkey-donkey** [comment]
any idea why dragging the indicator doesnt move the content?

**Comment by FanchenBao** [comment]
Because this feature was not implemented when I initially started the project.

**Comment by donkey-donkey** [comment]
is it a planned feature?

**Comment by FanchenBao** [comment]
Yes. I do want to include this feature, but it is very hard for me to give an estimate on when the feature will be ready.

**Comment by FanchenBao** [comment]
In the latest 0.3 release, content is now able to be scrolled by dragging the scroll indicator: #9
