### ISSUE TITLE
use native driver was not specified .

### ISSUE THREAD

**Issue by hussainali003** [FanchenBao/react-native-scroll-indicator#6]
react native --version "react-native": "0.72.5",
"react-native-scroll-indicator": "~0.1.0",

this is warning but so frustrating everytime , i scroll this warning was come and i dont know why.
![Screenshot (12)](https://github.com/FanchenBao/react-native-scroll-indicator/assets/37985459/cb7ae4e6-3180-44a9-9680-acf7ee14cd0a)

**Comment by FanchenBao** [comment]
I think you might be using the wrong package (this package's name is [@fanchenbao/react-native-scroll-indicator](https://www.npmjs.com/package/@fanchenbao/react-native-scroll-indicator)). Consider raising the issue on [react-native-scroll-indicator](https://github.com/mishabelokon/react-native-scroll-indicator#readme)
