### ISSUE TITLE
onScroll callback 

### ISSUE THREAD

**Issue by RediaUa** [FanchenBao/react-native-scroll-indicator#7]
I need to track the `contentOffset` position of `ScrollView`.
Could you pass event data to the callback from props in order to be able to get the event data outside?

The same is valid for the `onLayout`.

**Comment by FanchenBao** [comment]
Apologies for the late response and thanks for the feature request. I will look into it.

**Comment by FanchenBao** [comment]
Feature added in #14 with subsequent [v0.4.0 release](https://github.com/FanchenBao/react-native-scroll-indicator/releases/tag/v0.4.0)
