### ISSUE TITLE
Can't style parent div of scroll element

### ISSUE THREAD

**Issue by BrancuAlexandru** [FanchenBao/react-native-scroll-indicator#8]
Needs a way of styling parent div. Also should probably have an additional prop named indicatorStyle, since we've stopped shortening variable names... in 1990. Anyway, good project man I like it a lot.

**Comment by FanchenBao** [comment]
I will look into adding styling prop for the parent view that holds both the scrollable component and the indicator.

**Comment by FanchenBao** [comment]
Feature added in #12 with subsequent [v0.4.0 release](https://github.com/FanchenBao/react-native-scroll-indicator/releases/tag/v0.4.0)
